/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RestApiQualityApi);
  }
}(this, function(expect, RestApiQualityApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RestApiQualityApi.FileResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FileResponse', function() {
    it('should create an instance of FileResponse', function() {
      // uncomment below and update the code to test FileResponse
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be.a(RestApiQualityApi.FileResponse);
    });

    it('should have the property apiId (base name: "api-id")', function() {
      // uncomment below and update the code to test the property apiId
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be();
    });

    it('should have the property fileId (base name: "file-id")', function() {
      // uncomment below and update the code to test the property fileId
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be();
    });

    it('should have the property settingsId (base name: "settings-id")', function() {
      // uncomment below and update the code to test the property settingsId
      //var instane = new RestApiQualityApi.FileResponse();
      //expect(instance).to.be();
    });

  });

}));
