/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApplicationError', 'model/FileRequest', 'model/FileResponse', 'model/Swagger'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApplicationError'), require('../model/FileRequest'), require('../model/FileResponse'), require('../model/Swagger'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.FilesAPIApi = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.ApplicationError, root.RestApiQualityApi.FileRequest, root.RestApiQualityApi.FileResponse, root.RestApiQualityApi.Swagger);
  }
}(this, function(ApiClient, ApplicationError, FileRequest, FileResponse, Swagger) {
  'use strict';

  /**
   * FilesAPI service.
   * @module api/FilesAPIApi
   * @version 1.0.0
   */

  /**
   * Constructs a new FilesAPIApi. 
   * @alias module:api/FilesAPIApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the filesIdGet operation.
     * @callback module:api/FilesAPIApi~filesIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Swagger} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the raw swagger json as uploaded
     * @param {String} id 
     * @param {module:api/FilesAPIApi~filesIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Swagger}
     */
    this.filesIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling filesIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Swagger;

      return this.apiClient.callApi(
        '/files/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the filesPost operation.
     * @callback module:api/FilesAPIApi~filesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FileResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Upload a file
     * @param {module:model/FileRequest} file The file to upload
     * @param {module:api/FilesAPIApi~filesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FileResponse}
     */
    this.filesPost = function(file, callback) {
      var postBody = file;

      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling filesPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = FileResponse;

      return this.apiClient.callApi(
        '/files', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
