/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ApiRequest;
import io.swagger.model.ApplicationError;
import io.swagger.model.SettingsId;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-01-06T16:52:57.027Z")

@Api(value = "apis", description = "the apis API")
public interface ApisApi {

    @ApiOperation(value = "Get all available documents", notes = "", response = ApiRequest.class, responseContainer = "List", tags={ "APIs API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returned Documents", response = ApiRequest.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "Unexpected error", response = ApplicationError.class) })
    
    @RequestMapping(value = "/apis",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<ApiRequest>> apisGet();


    @ApiOperation(value = "Update the the settings of an API", notes = "", response = SettingsId.class, tags={ "APIs API", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returned Documents", response = SettingsId.class),
        @ApiResponse(code = 404, message = "API ID or Settings ID does not exist", response = ApplicationError.class),
        @ApiResponse(code = 500, message = "Unexpected error", response = ApplicationError.class) })
    
    @RequestMapping(value = "/apis/{id}/settings",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<SettingsId> apisIdSettingsPut(@ApiParam(value = "API ID",required=true ) @PathVariable("id") String id,@ApiParam(value = "The settings to use" ,required=true )  @Valid @RequestBody SettingsId file);

}
