/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/VersionRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./VersionRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.Api = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.VersionRequest);
  }
}(this, function(ApiClient, VersionRequest) {
  'use strict';




  /**
   * The Api model module.
   * @module model/Api
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Api</code>.
   * @alias module:model/Api
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Api</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Api} obj Optional instance to populate.
   * @return {module:model/Api} The populated <code>Api</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('api-id')) {
        obj['api-id'] = ApiClient.convertToType(data['api-id'], 'String');
      }
      if (data.hasOwnProperty('settings-id')) {
        obj['settings-id'] = ApiClient.convertToType(data['settings-id'], 'String');
      }
      if (data.hasOwnProperty('versions')) {
        obj['versions'] = ApiClient.convertToType(data['versions'], [VersionRequest]);
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} api-id
   */
  exports.prototype['api-id'] = undefined;
  /**
   * UUID of a setting
   * @member {String} settings-id
   */
  exports.prototype['settings-id'] = undefined;
  /**
   * @member {Array.<module:model/VersionRequest>} versions
   */
  exports.prototype['versions'] = undefined;



  return exports;
}));


