/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangeItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangeItem'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.Change = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.ChangeItem);
  }
}(this, function(ApiClient, ChangeItem) {
  'use strict';




  /**
   * The Change model module.
   * @module model/Change
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Change</code>.
   * @alias module:model/Change
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Change</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Change} obj Optional instance to populate.
   * @return {module:model/Change} The populated <code>Change</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('endpoint')) {
        obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('parameter')) {
        obj['parameter'] = ApiClient.convertToType(data['parameter'], [ChangeItem]);
      }
      if (data.hasOwnProperty('returntype')) {
        obj['returntype'] = ApiClient.convertToType(data['returntype'], [ChangeItem]);
      }
    }
    return obj;
  }

  /**
   * @member {String} endpoint
   */
  exports.prototype['endpoint'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Array.<module:model/ChangeItem>} parameter
   */
  exports.prototype['parameter'] = undefined;
  /**
   * @member {Array.<module:model/ChangeItem>} returntype
   */
  exports.prototype['returntype'] = undefined;



  return exports;
}));


