/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ComparisonReportResponsePaths'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ComparisonReportResponsePaths'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.ComparisonReportResponse = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.ComparisonReportResponsePaths);
  }
}(this, function(ApiClient, ComparisonReportResponsePaths) {
  'use strict';




  /**
   * The ComparisonReportResponse model module.
   * @module model/ComparisonReportResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ComparisonReportResponse</code>.
   * @alias module:model/ComparisonReportResponse
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ComparisonReportResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ComparisonReportResponse} obj Optional instance to populate.
   * @return {module:model/ComparisonReportResponse} The populated <code>ComparisonReportResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('file-ids')) {
        obj['file-ids'] = ApiClient.convertToType(data['file-ids'], ['String']);
      }
      if (data.hasOwnProperty('paths')) {
        obj['paths'] = ComparisonReportResponsePaths.constructFromObject(data['paths']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} file-ids
   */
  exports.prototype['file-ids'] = undefined;
  /**
   * @member {module:model/ComparisonReportResponsePaths} paths
   */
  exports.prototype['paths'] = undefined;



  return exports;
}));


