/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ComparisonReportResponse', 'model/ViolationReportResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ComparisonReportResponse'), require('./ViolationReportResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.RevisionReports = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.ComparisonReportResponse, root.RestApiQualityApi.ViolationReportResponse);
  }
}(this, function(ApiClient, ComparisonReportResponse, ViolationReportResponse) {
  'use strict';




  /**
   * The RevisionReports model module.
   * @module model/RevisionReports
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RevisionReports</code>.
   * @alias module:model/RevisionReports
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>RevisionReports</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RevisionReports} obj Optional instance to populate.
   * @return {module:model/RevisionReports} The populated <code>RevisionReports</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('violation')) {
        obj['violation'] = ViolationReportResponse.constructFromObject(data['violation']);
      }
      if (data.hasOwnProperty('comparison')) {
        obj['comparison'] = ApiClient.convertToType(data['comparison'], [ComparisonReportResponse]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ViolationReportResponse} violation
   */
  exports.prototype['violation'] = undefined;
  /**
   * @member {Array.<module:model/ComparisonReportResponse>} comparison
   */
  exports.prototype['comparison'] = undefined;



  return exports;
}));


