/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RevisionReports'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RevisionReports'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.Revision = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.RevisionReports);
  }
}(this, function(ApiClient, RevisionReports) {
  'use strict';




  /**
   * The Revision model module.
   * @module model/Revision
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Revision</code>.
   * @alias module:model/Revision
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Revision</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Revision} obj Optional instance to populate.
   * @return {module:model/Revision} The populated <code>Revision</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Date');
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = ApiClient.convertToType(data['file'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('reports')) {
        obj['reports'] = RevisionReports.constructFromObject(data['reports']);
      }
    }
    return obj;
  }

  /**
   * @member {Date} id
   */
  exports.prototype['id'] = undefined;
  /**
   * File UUID (compare /files API)
   * @member {String} file
   */
  exports.prototype['file'] = undefined;
  /**
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * @member {module:model/RevisionReports} reports
   */
  exports.prototype['reports'] = undefined;



  return exports;
}));


