/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.Violation = factory(root.RestApiQualityApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Violation model module.
   * @module model/Violation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Violation</code>.
   * Violation Object
   * @alias module:model/Violation
   * @class
   * @param title {String} 
   * @param description {String} 
   * @param violationType {String} 
   */
  var exports = function(title, description, violationType) {
    var _this = this;

    _this['title'] = title;
    _this['description'] = description;
    _this['violation_type'] = violationType;


  };

  /**
   * Constructs a <code>Violation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Violation} obj Optional instance to populate.
   * @return {module:model/Violation} The populated <code>Violation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('violation_type')) {
        obj['violation_type'] = ApiClient.convertToType(data['violation_type'], 'String');
      }
      if (data.hasOwnProperty('rule_link')) {
        obj['rule_link'] = ApiClient.convertToType(data['rule_link'], 'String');
      }
      if (data.hasOwnProperty('paths')) {
        obj['paths'] = ApiClient.convertToType(data['paths'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} violation_type
   */
  exports.prototype['violation_type'] = undefined;
  /**
   * @member {String} rule_link
   */
  exports.prototype['rule_link'] = undefined;
  /**
   * @member {Array.<String>} paths
   */
  exports.prototype['paths'] = undefined;



  return exports;
}));


