/**
 * REST-API Quality API
 * API for determing the Quality of REST APIs
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Violation', 'model/ViolationsCount'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Violation'), require('./ViolationsCount'));
  } else {
    // Browser globals (root is window)
    if (!root.RestApiQualityApi) {
      root.RestApiQualityApi = {};
    }
    root.RestApiQualityApi.ViolationReportResponse = factory(root.RestApiQualityApi.ApiClient, root.RestApiQualityApi.Violation, root.RestApiQualityApi.ViolationsCount);
  }
}(this, function(ApiClient, Violation, ViolationsCount) {
  'use strict';




  /**
   * The ViolationReportResponse model module.
   * @module model/ViolationReportResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ViolationReportResponse</code>.
   * Linting Response
   * @alias module:model/ViolationReportResponse
   * @class
   * @param violations {Array.<module:model/Violation>} 
   */
  var exports = function(violations) {
    var _this = this;

    _this['violations'] = violations;


  };

  /**
   * Constructs a <code>ViolationReportResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ViolationReportResponse} obj Optional instance to populate.
   * @return {module:model/ViolationReportResponse} The populated <code>ViolationReportResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('violations')) {
        obj['violations'] = ApiClient.convertToType(data['violations'], [Violation]);
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('violations_count')) {
        obj['violations_count'] = ViolationsCount.constructFromObject(data['violations_count']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/Violation>} violations
   */
  exports.prototype['violations'] = undefined;
  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {module:model/ViolationsCount} violations_count
   */
  exports.prototype['violations_count'] = undefined;



  return exports;
}));


